[package]
name = "terminal-arcade"
version = "0.1.0"
authors = ["Ramen Developer <ramendev2009@gmail.com>"]
edition = "2021"
rust-version = "1.64.0"
description = "Terminal-based arcade-style games for when you're bored out of your mind."
documentation = "documentation? what documentation?"
readme = "README.md"
homepage = "homepage? what homepage?"
repository = "https://github.com/developer-ramen/terminal-arcade"
license = "MIT"
keywords = ["arcade", "terminal", "games"]
categories = ["arcade", "terminal", "games"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.1.2"
ansi-to-tui = "3.0.0"
anyhow = "1.0.70"
chrono = "0.4.24"
crossterm = { version = "0.26.1", features = ["event-stream"] }
derive-new = "0.5.9"
derive_builder = "0.12.0"
git_info = "0.1.2"
home = "0.5.5"
once_cell = "1.17.1"
pluralizer = "0.4.0"
rand = "0.8.5"
ratatui = "0.21.0"
serde = "1.0.160"
serde_derive = "1.0.160"
thiserror = "1.0.40"
tiny-gradient = "0.1.0"
toml = "0.7.3"
