[package]
name = "terminal-arcade"
version = "0.1.0"
authors = ["Ramen Developer <ramendev2009@gmail.com>"]
edition = "2021"
rust-version = "1.68.0"
description = "Terminal-based arcade games for when you're bored out of your mind."
documentation = "documentation? what documentation?"
readme = "README.md"
homepage = "homepage? what homepage?"
repository = "https://github.com/developer-ramen/terminal-arcade"
license = "MIT"
keywords = ["arcade", "terminal", "games"]
categories = ["arcade", "terminal", "games"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-to-tui = "3.0.0"
anyhow = "1.0.70"
crossterm = { version = "0.26.1", features = ["event-stream"] }
derive-new = "0.5.9"
new = "0.0.0"
once_cell = "1.17.1"
ratatui = "0.20.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1.0.40"
tiny-gradient = "0.1.0"
toml = "0.7.3"
